function varargout = anaBlobs(vid_path,v,opType,varargin)
% Analyze blobs that may be extracted from a video
% B = anaBlobs(vid_path,v,opType)
%  B - structure of blob data
%  vid_path - path to video file or image sequence
%  v - structure of info about video (generated by defineVidObject)
%  opType - designates the type of operation ('G&L props')
%
% B = anaBlobs(vid_path,v,'G&L props',S,blobParam,imInvert,imRoiMean)
% Finds the global and local parameters for blobs
%   im_seq - 3D sequence if images in the roi
%   fr_num - sequence of frame numbers to be included in mean image
%   Centroid - struction denoting the center of the roi (generated by tracker)
%   Rotation - rotation structure generated by tracker
%   blobParam - Structure of blob parameters
%   imInvert - logical that indicates whether to invert images
%
% % B = anaBlobs(vid_path,v,'filter motion',B,winLen,Centroid,...
%       Rotation,blobParam,tVal)
%   tVal - threshold value for blobs
%
% Developed by McHenryLab at UC Irvine


%% Parse inputs

if strcmp(opType,'G&L props')
   
    % Extract inputs
    %im_seq    = varargin{1};
    S  = varargin{1};
    %Rotation  = varargin{4};
    blobParam = varargin{2};
    imInvert  = varargin{3};
    dSample   = varargin{4};
    imRoiMean = varargin{5};

elseif strcmp(opType,'filter motion')
    
    % Extract inputs
    B         = varargin{1};
    winLen    = varargin{2};
    S         = varargin{3};
    blobParam = varargin{4};
    tVal      = varargin{5};
    
    dSample = 0;
    imInvert = 0;
    
else
    error('opType not recognized');
end


%% Loop thru frames ('G&L props')

if strcmp(opType,'G&L props')
    
    % Loop thru frames
    for i = 1:length(S.frames)
        
        % Current frame
        cFrame = S.frames(i);
        
        % Index for current frame in the data
        %iFrame = find(S.frames==cFrame);

        % Current whole frame
        im = getFrame(vid_path,v,cFrame,imInvert,'gray');

        % Roi image, mean image subtracted
        [im_roi,bw_mask,bw_roi_mask] = giveROI('stabilized',im,...
            S.roi(i),dSample,S.tform(:,:,i),imRoiMean);
        
        % Find blobs in roi
        [props,bw_roi,areas,xB,yB] = findBlobs(im_roi,blobParam.tVal,...
            'area and circ',blobParam.areaMin,blobParam.areaMax,blobParam.AR_max);
        
        % Get roi data
        %[bw_mask,im_roi,roi_rect,bw_roi_mask] = giveROI('circular',im,x,y,r,theta,0);
        
        % Blobs in the G FOR
        bw_blobs_G = transCoord2d('bw L2G',S.tform(:,:,i),bw_roi,bw_mask,bw_roi_mask);
        
        % Survey blobs
        propsG = regionprops(bw_blobs_G,'Centroid','Area',...
            'MajorAxisLength','MinorAxisLength',...
            'PixelIdxList','PixelList');
        
        % Store blob data
        B(i).fr_num = cFrame;
        B(i).propsG = propsG;
        B(i).propsL = props;
        
        if 0
            % Current whole frame
            imI = getFrame(vid_path,v,cFrame,~imInvert,'gray');
            
            h = imshow(imI,'InitialMag','fit');
            hold on
            
            % Make a truecolor all-green image, make non-blobs invisible
            green = cat(3, zeros(size(im)), ones(size(im)), zeros(size(im)));
            h = imshow(green,'InitialMag','fit');
            set(h, 'AlphaData', bw_blobs_G)
            
            title(['Frame ' num2str(fr_num(i))]);
            
            pause(0.001)
            
        else
            disp(['anaBlobs (' opType ') : '  num2str(i) ' of ' num2str(length(S.frames))]);
        end
        
        clear props propsG bw_mask im_roi roi_rect bw_roi_mask bw_roi
        clear areas xB yB
    end   
end


%% Loop thru frames ('filter motion')

if strcmp(opType,'filter motion')
        
    Bin = B;
    clear B

    % Half interval to survey for analysis
    halfIntvl = floor(winLen/2);
    
    % Fill 
    for i = 1:halfIntvl-1
        B(i).fr_num = Bin(i).fr_num;
        %B(i).frIdx  = Bin(i).frIdx;
        B(i).propsG = nan;
        B(i).propsL = nan;
    end
    
    for i = (halfIntvl+1):(length(Bin)-halfIntvl-1)
        
        % Current frame
        cFrame = Bin(i).fr_num;
        
        % Index for current frame in the data
        %iFrame = Bin(i).frIdx;
        iFrame = i;
        
        % Current whole frame
        %im = getFrame(vid_path,v,cFrame,imInvert,'gray');
        
        % Window of frames to analyze
        startFrame = max([1 cFrame-halfIntvl]);
        endFrame = min([max(S.frames) cFrame+halfIntvl]);       
        winFrames = startFrame:endFrame;
        
        % Produce image that highlights static elements
        imB = motionImage(vid_path,v,'bw static',winFrames,Bin);

        %tVal = imInteract(imcomplement(imStackScore),'threshold');
        %tVal = 0.5871;
        
%         bwNew = im2bw(imB,tVal);
%         
%         % Fill holes
%         bwNew = ~imfill(~bwNew,'holes');
%         
%         % Check input
%         if min(bwNew(:))==1
%             error('You need to adjust threshold -- no blobs in image');
%         end
        
         % Survey blobs
%         propsG = regionprops(~bwNew,'Centroid','Area',...
%             'MajorAxisLength','MinorAxisLength',...
%             'PixelIdxList','PixelList');
        
        % Find blobs in image
        [propsG,bw_im] = findBlobs(imB,tVal,...
                         'area and circ',blobParam.areaMin,...
                         blobParam.areaMax,blobParam.AR_max);

        % Get roi data
        %[bw_mask,im_roi,roi_rect,bw_roi_mask] = giveROI('circular',imB,x,y,r,theta,0);
        im_roi = giveROI('stabilized',imB,S.roi(i),dSample, ...
                S.tform(:,:,i));
        
        % Find blobs in roi
        [propsL,bw_roi] = findBlobs(im_roi,blobParam.tVal,...
                         'area and circ',blobParam.areaMin,...
                         blobParam.areaMax,blobParam.AR_max);
        
        % Store blob data
        B(i).fr_num = cFrame;
        B(i).frIdx  = iFrame;
        B(i).propsG = propsG;
        B(i).propsL = propsL;

        % Status report
        disp(' ')
        disp(['anaBlobs (' opType ') : done ' num2str(i) ' of ' ...
              num2str((length(Bin)-halfIntvl))])
        disp(' ');
        
        clear im_roi im bw_roi bw_im propsG propsL
    end
    
        
end

%% Outputs

varargout{1} = B;




